
module.exports = {
  up: (queryInterface, Sequelize) => {

    return queryInterface.bulkInsert('Users', [
      {
        id: 1,
        userNickname: 'Emma',
        userFirstJob: '네이버 디자이너', userSecondJob: '캠프모바일 기획자',
        introduction: 'Emma 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Emma',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_01.png',
        highfiveNumber: 16,
        passNumber: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 2,
        userNickname: 'Emily',
        userFirstJob: 'SKTechX 개발자',
        introduction: 'Emily 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Emily',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_02.png',
        highfiveNumber: 27,
        passNumber: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 3,
        userNickname: 'Madison',
        userFirstJob: 'Nexon 영상 디자이너', userSecondJob: '네이버 영상 디자이너', userThirdJob: '네이버 연구원',
        introduction: 'Madison 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Madison',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_03.png',
        highfiveNumber: 128,
        passNumber: 7,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 4,
        userNickname: 'Olivia',
        userFirstJob: 'Amazon 개발자', userSecondJob: 'SKTechX 개발자',
        introduction: 'Olivia 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Olivia',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_04.png',
        highfiveNumber: 30,
        passNumber: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 5,
        userNickname: 'Abigail',
        userFirstJob: '대학생', userSecondJob: '구글 선임 연구원', userThirdJob: 'SKTechX 개발자',
        introduction: 'Abigail 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Abigail',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_05.png',
        highfiveNumber: 21,
        passNumber: 10,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 6,
        userNickname: 'Alexis',
        userFirstJob: '삼성전자 기획자',
        introduction: 'Alexis 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Alexis',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_06.png',
        highfiveNumber: 312,
        passNumber: 9,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 7,
        userNickname: 'Ashley',
        userFirstJob: 'Amazon 개발자', userSecondJob: '구글 디자이너', userThirdJob: '블리자드 디자이너',
        introduction: 'Ashley 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Ashley',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_07.png',
        highfiveNumber: 128,
        passNumber: 11,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 8,
        userNickname: 'Samantha',
        userFirstJob: '스타벅스 기획자',
        introduction: 'Samantha 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Samantha',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_08.png',
        highfiveNumber: 19,
        passNumber: 12,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 9,
        userNickname: 'Beth',
        userFirstJob: 'SKTechX 개발자',
        introduction: 'Beth 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Beth',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_09.png',
        highfiveNumber: 0,
        passNumber: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 10,
        userNickname: 'Bess',
        userFirstJob: '삼성 연구원', userSecondJob: '네이버 디자이너',
        introduction: 'Bess 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Bess',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_10.png',
        highfiveNumber: 21,
        passNumber: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 11,
        userNickname: 'Betsy',
        userFirstJob: 'SKTelecom 개발자', userSecondJob: '샤오미 연구원',
        introduction: 'Betsy 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Betsy',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_11.png',
        highfiveNumber: 31,
        passNumber: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 12,
        userNickname: 'Betty',
        userFirstJob: '구글 개발자', userSecondJob: '애플 디자이너', userThirdJob: 'SKTechX 개발자',
        introduction: 'Betty 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Betty',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_12.png',
        highfiveNumber: 32,
        passNumber: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 13,
        userNickname: 'Bette',
        userFirstJob: '마이크로소프트 개발자', userSecondJob: '블리자드 개발자', userThirdJob: '세가 개발자',
        introduction: 'Bette 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Bette',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_13.png',
        highfiveNumber: 18,
        passNumber: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 14,
        userNickname: 'Buffy',
        userFirstJob: '네이버 디자이너',
        introduction: 'Buffy 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Buffy',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_14.png',
        highfiveNumber: 22,
        passNumber: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 15,
        userNickname: 'Eliza',
        userFirstJob: '쿠팡 디자이너', userSecondJob: '구글 디자이너', userThirdJob: '애플 개발자',
        introduction: 'Eliza 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Eliza',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_15.png',
        highfiveNumber: 123,
        passNumber: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 16,
        userNickname: 'Elle',
        userFirstJob: 'IBM 개발자',
        introduction: 'Elle 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Elle',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_16.png',
        highfiveNumber: 1257,
        passNumber: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 17,
        userNickname: 'Elsie',
        userFirstJob: '서울대학교 연구원', userSecondJob: '고려대학교 학생',
        introduction: 'Elsie 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Elsie',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_17.png',
        highfiveNumber: 31,
        passNumber: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 18,
        userNickname: 'Elsa',
        userFirstJob: 'CJ 연구원', userSecondJob: '연세대학교 연구원', userThirdJob: '네이버 디자이너',
        introduction: 'Elsa 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Elsa',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_18.png',
        highfiveNumber: 24,
        passNumber: 12,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 19,
        userNickname: 'Izzy',
        userFirstJob: '쿠팡 개발자', userSecondJob: 'SKTechX 개발자',
        introduction: 'Izzy 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Izzy',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_19.png',
        highfiveNumber: 742,
        passNumber: 11,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 20,
        userNickname: 'Liz',
        userFirstJob: '카카오 개발자',
        introduction: 'Liz 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Liz',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_20.png',
        highfiveNumber: 31,
        passNumber: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 21,
        userNickname: 'Lisa',
        userFirstJob: '페이스북 개발자', userSecondJob: '애플 디자이너',
        introduction: 'Lisa 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Lisa',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_19.png',
        highfiveNumber: 51,
        passNumber: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 22,
        userNickname: 'Liza',
        userFirstJob: '샤오미 디자이너', userSecondJob: '네이버 디자이너',
        introduction: 'Liza 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Liza',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_18.png',
        highfiveNumber: 67,
        passNumber: 7,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 23,
        userNickname: 'Lizbeth',
        userFirstJob: 'KT 선임 연구원', userSecondJob: '플리토 개발자', userThirdJob: '아마존 기획자',
        introduction: 'Lizbeth 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Lizbeth',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_17.png',
        highfiveNumber: 333,
        passNumber: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 24,
        userNickname: 'Lise',
        introduction: 'Lise 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Lise',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_16.png',
        highfiveNumber: 243,
        passNumber: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 25,
        userNickname: 'Liddy',
        userFirstJob: '구글 개발자', userSecondJob: '네이버 디자이너',
        introduction: 'Liddy 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Liddy',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_15.png',
        highfiveNumber: 0,
        passNumber: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 26,
        userNickname: 'Sammy',
        introduction: 'Sammy 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Sammy',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_14.png',
        highfiveNumber: 1,
        passNumber: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 27,
        userNickname: 'Bella',
        userFirstJob: '샤오미 디자이너', userSecondJob: '마이크로소프트 개발자', userThirdJob: '페이스북 개발자',
        introduction: 'Bella 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Bella',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_13.png',
        highfiveNumber: 0,
        passNumber: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 28,
        userNickname: 'Grace',
        userFirstJob: '쿠팡 디자이너', userSecondJob: '페이스북 개발자',
        introduction: 'Grace 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Grace',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_12.png',
        highfiveNumber: 12,
        passNumber: 9,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 29,
        userNickname: 'Lauren',
        introduction: 'Lauren 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Lauren',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_11.png',
        highfiveNumber: 43,
        passNumber: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 30,
        userNickname: 'Kayla',
        userFirstJob: '페이스북 디자이너',
        introduction: 'Kayla 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Kayla',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_10.png',
        highfiveNumber: 123,
        passNumber: 10,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 31,
        userNickname: 'Briana',
        userFirstJob: '베스티 개발자', userSecondJob: 'SKTechX 개발자',
        introduction: 'Briana 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Briana',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_09.png',
        highfiveNumber: 222,
        passNumber: 11,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 32,
        userNickname: 'Jessie',
        userFirstJob: '오라클 개발자', userSecondJob: 'IBM 개발자', userThirdJob: '삼성SDS 개발자',
        introduction: 'Jessie 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Jessie',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_08.png',
        highfiveNumber: 432,
        passNumber: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 33,
        userNickname: 'Jess',
        userFirstJob: '쿠팡 디자이너', userSecondJob: '페이스북 디자이너',
        introduction: 'Jess 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Jess',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_07.png',
        highfiveNumber: 321,
        passNumber: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 34,
        userNickname: 'Taylor',
        introduction: 'Taylor 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Taylor',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_06.png',
        highfiveNumber: 1000,
        passNumber: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 35,
        userNickname: 'Sophia',
        userFirstJob: 'NCSoft 디자이너', userSecondJob: '넥슨 디자이너',
        introduction: 'Sophia 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Sophia',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_05.png',
        highfiveNumber: 999,
        passNumber: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 36,
        userNickname: 'Victoria',
        userFirstJob: '오라클 디자이너', userSecondJob: 'NCSoft 디자이너', userThirdJob: '넷마블 디자이너',
        introduction: 'Victoria 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Victoria',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_04.png',
        highfiveNumber: 312,
        passNumber: 9,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 37,
        userNickname: 'Vicky',
        introduction: 'Vicky 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Vicky',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_03.png',
        highfiveNumber: 242,
        passNumber: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 38,
        userNickname: 'Tori',
        userFirstJob: '트렐로 개발자', userSecondJob: '구글 개발자',
        introduction: 'Tori 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Tori',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_02.png',
        highfiveNumber: 100,
        passNumber: 11,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 39,
        userNickname: 'Vivi',
        introduction: 'Vivi 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Vivi',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_01.png',
        highfiveNumber: 99,
        passNumber: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 40,
        userNickname: 'Jasmine',
        introduction: 'Jasmine 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Jasmine',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_02.png',
        highfiveNumber: 12,
        passNumber: 12,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 41,
        userNickname: 'Rachael',
        userFirstJob: '쿠팡 개발자', userSecondJob: '네이버 개발자',
        introduction: 'Rachael 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Rachael',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_03.png',
        highfiveNumber: 1,
        passNumber: 13,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 42,
        userNickname: 'Jaz',
        userFirstJob: '카카오 개발자',
        introduction: 'Jaz 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Jaz',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_04.png',
        highfiveNumber: 13,
        passNumber: 18,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 43,
        userNickname: 'Minnie',
        userFirstJob: 'SKTelecom 개발자', userSecondJob: '카카오 개발자',
        introduction: 'Minnie 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Minnie',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_05.png',
        highfiveNumber: 24,
        passNumber: 17,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 44,
        userNickname: 'Morgan',
        introduction: 'Morgan 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Morgan',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_06.png',
        highfiveNumber: 31,
        passNumber: 22,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 45,
        userNickname: 'Megan',
        userFirstJob: 'CJ 기획자', userSecondJob: '현대모비스 디자이너', userThirdJob: '카카오 개발자',
        introduction: 'Megan 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Megan',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_07.png',
        highfiveNumber: 24,
        passNumber: 31,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 46,
        userNickname: 'Jen',
        userFirstJob: '샤오미 디자이너',
        introduction: 'Jen 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Jen',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_08.png',
        highfiveNumber: 100,
        passNumber: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 47,
        userNickname: 'Jenny',
        userFirstJob: '샤오미 개발자', userSecondJob: '텐센트 디자이너', userThirdJob: '오라클 개발자',
        introduction: 'Jenny 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Jenny',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_09.png',
        highfiveNumber: 0,
        passNumber: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 48,
        userNickname: 'Hayley',
        userFirstJob: '카카오 디자이너', userSecondJob: '애플 개발자', userThirdJob: '현대 기획자',
        introduction: 'Hayley 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Hayley',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_10.png',
        highfiveNumber: 0,
        passNumber: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 49,
        userNickname: 'Mills',
        userFirstJob: '카카오 개발자',
        introduction: 'Mills 소개글입니다.',
        portfolio: 'http://www.portfolio.com/Mills',
        userImage: 'https://s3.ap-northeast-2.amazonaws.com/appmate2017/initimage/dummy_profile_11.png',
        highfiveNumber: 0,
        passNumber: 9,
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ], {});
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkDelete('Person', null, {});
    */
  }
};
